### ISSUE TITLE
Clipboard in codespace

### ISSUE THREAD

**Issue by rich-byte** [2start/gptprep#1]
I like the plugin, it works great with repos stored locally on my machine. However, when I open a Codespace in VS Code it seems to run but not copy anything to the clipboard. I'm not sure how the clipboard works in Codespaces and whether it is possible or worth looking into supporting it.

Steps to reproduce:
Open any Codespace in VS Code.
Install gptprep 
Run gptprep

**Comment by klaudworks** [comment]
Thanks for the feedback, I'll look into it!
